### ISSUE TITLE
Where are the project files, where is the gitignore

### ISSUE THREAD

**Issue by insomnyawolf** [WhiteRedWolf/hikari.game#2]
Check and add this so you dont mix executable binary files in your code.

https://git.xii.nz/insomnyawolf/OsuPatcher/raw/branch/master/.gitignore

Also Theres no project folder with .sln file, its all mixed up.

**Comment by WhiteRedWolf** [comment]
i dont kow what .gitignore does, could you please tell me what it does and how it helps? and i will delete the executables soon, and the sln file will mix all folders so it does not make any sense to include it.

**Comment by insomnyawolf** [comment]
Gitignore make files like Configuration file (wich may have passwords as example) or binary files ignored by github so they doesnt get commited- uploaded to the rep

**Comment by WhiteRedWolf** [comment]
i am not needing that
